library("dplyr")
library("tidyr")



## What is clean data in R? ##

## GROUND RULES FOR HOW R WORKS WITH DATASETS BEST ##
## 1) Each variable in the data set is placed in its own column
## 2) Each observation is placed in its own row
## 3) Each value is placed in its own cell



######### TIDYR ###########
## This package helps you get your data to R specs
## gather(), separate(), unite(), spread()
## both rely on key value pairs

### GATHER FUNCTION ###
?gather

messy1 = data.frame(
  name = c("Wilbur", "Petunia", "Gregory"),
  a = c(67, 80, 64),
  b = c(56, 90, 50),
  c = c(99, 30, 40)
)

## what's wrong with this data? 
## this data is considered WIDE since heartrate is in multiple columns
## first identify the variables: name, drug, heart rate
## Do they follow the rules of tidyr?
messy1 = gather(messy1, drug, heartrate,a,b,c)
messy1


### SEPARATE FUNCTION ###
?separate
messy2 = data.frame(
  name = c("Wilbur_m", "Petunia_f", "Gregory_m"),
  a = c(67, 80, 64),
  b = c(56, 90, 50),
  c = c(99, 30, 40)
)

messy2 = separate(messy2, name, c("name","gender"), sep="_")
messy2 = gather(messy2, drug, heartrate,a,b,c)
messy2


### UNITE FUNCTION ###
?unite
messy3 = data.frame(
  first_name = c("Wilbur_m", "Petunia_f", "Gregory_m"),
  last_name = c("Smith", "Gordon", "Jones"),
  a = c(67, 80, 64),
  b = c(56, 90, 50),
  c = c(99, 30, 40)
)

messy3 = gather(messy3, drug, heartrate,a,b,c)
messy3 = separate(messy3, first_name, c("first_name","gender"), sep="_")
messy3 = unite(messy3, full_name, 1, 3, sep=" ")
messy3


### SPREAD FUNCTION ###
?spread
messy3 = spread(messy3, drug, heartrate)
messy3













?read.csv

## http://www.listendata.com/2016/08/dplyr-tutorial.html

## dplyr is similar to sql statements (select, group by, joins)
library("dplyr")
library("tidyr")
## look at sample data set, income generated by states from 2002 to 2015
mydata = read.csv("assets/sales_per_year_per_state.csv")
View(mydata)

tidy_data = gather(mydata, year, sales_amount, Y2002:Y2015)
View(mydata2)

######### SAMPLE FUNCTION ###########

## select random rows by defining the number of rows you want
s1 = sample_n(mydata, 5)
s1
## re-run this and you will get a different random 5 every time


## select random rows by defining a percentage
## this will be more helpful when using predictive algorithms
s2 = sample_frac(mydata, 0.2)
s2



######### SELECT FUNCTION ###########
## pre-req: data must be in data frame format because it uses columns as params

## from the df, get index and state through y2008
mydata2 = select(mydata, Index, State:Y2008)




## from the df, drop variables
mydata3 = select(mydata, -Index, -State)





## select variables based on partial description
mydata4 = select(mydata, starts_with("Y"))

## drop
mydata5 = select(mydata, -starts_with("Y"))

## rearrange the data, put state as the first column
mydata6 = select(mydata, State, everything())






######### RENAME FUNCTION ###########
## must be a data frame
## provide new name first, then old name that it is replacing
renamed_data = rename(mydata, my_awesome_index=Index)








######### FILTER FUNCTION ###########

## single criteria
filtered_data = filter(mydata, Index=="A")
filtered_data


## multiple criteria
multi_select_data1 = filter(mydata, Index %in% c("A", "C"))
multi_select_data1



multi_select_data2 = filter(mydata, Index %in% c("A", "C") & Y2002 >= 1400000)
multi_select_data2




multi_select_data3 = filter(mydata, Index %in% c("A", "C") | Y2002 >= 1900000)
multi_select_data3





## not operator
not_op_filtered_data = filter(mydata, !Index =="A")
not_op_filtered_data







######### ARRANGE FUNCTION ###########
## arrange is used to carry out sorting operations
arrange(mydata, desc(Index))
arrange(mydata, Index, desc(Y2002))












######### MUTATE FUNCTION ###########
## talk about feature engineering

## adding a new var named change
mutate(mydata, perc_change=Y2015/Y2014)

## mutate all variables
mutate_all(mydata, funs("new"=.*1000))

######### OTHER THINGS DPLYR CAN DO ###########
## join()
## intersect()
## union()












shoes = read.csv("assets/ZapataShoes.csv")
View(shoes)
head(shoes)

## get a sample of 10% of the whole dataset

## drop customer number column

## get all buyers from Los Angeles

## get all buyers who purchased the Praia shoe

## separate name into first name and last name columns. NOTE: we'll go over this one together, but try. You might need another package.


## SOLUTIONS

shoes_samp = sample_frac(shoes, .10)

shoes_samp = select(shoes_samp, -CustNbr)

LA_customers = filter(shoes_samp, City == "Los Angeles")

Praia_shoe_customers = filter(shoes_samp, Shoe=="Praia")

library(tidyr)
shoes_samp = separate(shoes_samp, Name, c("Last_Name", "First_Name"), sep=",")
head(shoes_samp)



